# Generated by Django 5.1.8 on 2025-04-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_price', models.PositiveIntegerField(default=0, help_text='به تومان', verbose_name='هزینه ی ارسال')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=7, default=1.0, max_digits=12, verbose_name='تعداد')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='carts.cart', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم سبد خرید',
            },
        ),
    ]
