# Generated by Django 5.1.8 on 2025-04-24 18:00

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('value', models.CharField(max_length=250, verbose_name='مقدار')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_message', models.TextField(blank=True, null=True, verbose_name='اعلانات')),
                ('admin_phone_number', models.CharField(help_text='برای ارسال پیام های اطلاع رسانی و سفارش جدید.', max_length=11, validators=[utils.validators.persian_phone_number_validation], verbose_name='شماره موبایل ادمین')),
                ('fast_send_price', models.PositiveIntegerField(default=0, help_text='به تومان', verbose_name='هزینه ی ارسال فوری')),
                ('pay_with_mellat', models.BooleanField(default=True, verbose_name='درگاه ملت')),
                ('pay_with_parsian', models.BooleanField(default=True, verbose_name='درگاه پارسیان')),
                ('pay_at_home', models.BooleanField(default=True, verbose_name='پرداخت درب منزل')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(help_text='عکس برای بنر', upload_to='banners/', verbose_name='بنر')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='site_settings.sitesettings')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_settings.base')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='site_settings.sitesettings')),
            ],
            bases=('site_settings.base',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_settings.base')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='site_settings.sitesettings')),
            ],
            bases=('site_settings.base',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_settings.base')),
                ('setting', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='site_settings.sitesettings')),
            ],
            bases=('site_settings.base',),
        ),
    ]
