# Generated by Django 5.1.8 on 2025-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'در انتظار پرداخت'), ('2', 'پرداخت درب منزل'), ('3', 'پرداخت شده'), ('4', 'ارسال شده'), ('5', 'تحویل داده شده'), ('6', 'لغو شده')], default='در انتظار پرداخت', max_length=20, verbose_name='وضعیت'),
        ),
    ]
