# Generated by Django 5.1.8 on 2025-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=12, verbose_name='تعداد'),
        ),
    ]
